# -*- coding: utf-8 -*-
"""create_tdml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/148B7hETuUrnWKDCJFoVHjbzWg2gDXIAo

<details><summary>Example</summary>

```json
{
  "type": "AI_AbstractTrainingDataset",
  "id": "udt_hf24",
  "name": "UDT_HF24",
  "description": "Training dataset formulated from GeoPose data that was based on the Hillyfield frame dataset",
  "version": "1.0",
  "amountOfTrainingData": 335,
  "createdTime": "<DATE KALP CREATED GEOPOSE DATA>",
  "providers": [
    "University of Central Florida"
  ],
  "dataSources": [
    {
      "title": "<NAME OF ORG THAT COLLECTED HILLYFIELD DATA>",
      "date": "2013-04-21"
    }
  ],
  "numberOfClasses": 4,
  "classes": [
    {
      "key": "asphault",
      "value": 0
    },
    {
      "key": "dirt",
      "value": 1
    },
    {
      "key": "gravel",
      "value": 2
    },
    {
      "key": "concrete",
      "value": 3
    },
  ],
  "tasks": [
    {
      "type": "AI_AbstractTask",
      "id": "road-surface-classification-task",
      "description": "Classifying images based on road surface shown."
    },
  ],
  "data": [
    {
      "type": "AI_AbstractTrainingData",
      "id": "img0001",
      "dataURL": ["hillyfields_dataset/images/Front/img0001.png"],
      "labels": [{"type": "AI_SceneLabel", "class": "footway"}]
    },
    {
      "type": "AI_AbstractTrainingData",
      "id": "img0002",
      "dataURL": ["hillyfields_dataset/images/Front/img0002.png"],
      "labels": [{"type": "AI_SceneLabel", "class": "footway"}]
    },
    ...
    {
      "type": "AI_AbstractTrainingData",
      "id": "img0150",
      "dataURL": ["hillyfields_dataset/images/Front/img0150.png"],
      "labels": [{"type": "AI_SceneLabel", "class": "unclassified"}]
    },
    ...
    {
      "type": "AI_AbstractTrainingData",
      "id": "img0335",
      "dataURL": ["hillyfields_dataset/images/Front/img0335.png"],
      "labels": [{"type": "AI_SceneLabel", "class": "footway"}]
    },
  ]
}
```

</details>
"""

from google.colab import drive
from datetime import datetime
import pandas as pd
import json
import re

"""# Mount Google Drive"""

# Commented out IPython magic to ensure Python compatibility.
drive.mount('/content/drive')
# %cd /content/drive/MyDrive/D102_PoC

"""# Load Input Files

## GeoPose
"""

# Enter path to geopose file
geopose_file = 'tdml_input_data/ucf_09-14-24/GeoPose_SensorLogger_Seq_Series_Regular.json'

# Get contents of geopose file
with open(geopose_file, 'r') as f:
    # convert to json object
    geopose_data = json.load(f)
    f.close()

# Print info about geopose data
print(json.dumps(geopose_data['header'], indent=2))

"""## Annotations

Input is a JSON annotation file following the COCO 1.0 standard.
"""

annotations_file = 'tdml_input_data/ucf_09-14-24/annotations/annotations_relabeled.json'

# Get contents of geopose file
with open(annotations_file, 'r') as f:
    # convert to json object
    annotation_data = json.load(f)
    f.close()

# Print annotation classes
print(json.dumps(annotation_data['categories'], indent=2))

"""## Synchronized Dataframe"""

synced_ins_file = 'tdml_input_data/ucf_09-14-24/synchronized_df.csv'

# Get contents of geopose file
with open(synced_ins_file, 'r') as f:
    # convert to json object
    ins_data = pd.read_csv(f)
    f.close()

# Print the first few rows of the INS data
ins_data.head()

"""# Enter Metadata"""

dataset_type = "AI_AbstractTrainingDataset" # @param ["AI_AbstractTrainingDataset","AI_EOTrainingDataset"]
dataset_id = "udt_ucf24" # @param {"type":"string"}
dataset_name = "UDT_UCF24" # @param {"type":"string"}
dataset_description = "Training dataset formulated from GeoPose data that was based on firsthand data collected at the University of Central Florida" # @param {"type":"string"}
dataset_license = "CC BY-SA 4.0" # @param {"type":"string"}
dataset_version = "1.0" # @param {"type":"string"}
dataset_providers = ["University of Central Florida"] # @param {"type":"raw"}
dataset_task = "AI_AbstractTask" # @param ["AI_AbstractTask","AI_EOTask"]
dataset_task_id = "ucf-udt-task" # @param {"type":"string"}
dataset_task_description = "Classifying images based on road surface shown." # @param {"type":"string"}
dataset_task_type = "Road Surface Classification Task" # @param {"type":"string"}

dataset_datasources = [
    {
      "title": "Urban Digital Twin Lab: UCF Roads (Prelimenary)",
      "date": "2024-09-13"
    }
  ]

"""# Populate TDML Information"""

# Object that will store all tdml data
tdml_object = {}

"""## 1. Metadata"""

tdml_object['type'] = dataset_type
tdml_object['id'] = dataset_id
tdml_object['name'] = dataset_name
tdml_object['description'] = dataset_description
tdml_object['license'] = dataset_license
tdml_object['version'] = dataset_version
tdml_object['providers'] = dataset_providers
tdml_object['dataSources'] = dataset_datasources

tdml_object['tasks'] = [
    {
      'type': dataset_task,
      'id': dataset_task_id,
      'description': dataset_task_description
    }
]

"""### Computed values"""

timestamp = geopose_data['header']['startInstant']

# convert timestamp to ISO8601 format
tdml_object['createdTime'] = str(datetime.fromtimestamp(timestamp / 1000000))
tdml_object['amountOfTrainingData'] = len(annotation_data['images'])
tdml_object['numberOfClasses'] = len(annotation_data['categories'])

"""## 2. Classes"""

tdml_classes = []

for category in annotation_data['categories']:
  tdml_classes.append({
      'key': category['name'],
      'value': category['id']
  })

tdml_object['classes'] = tdml_classes

"""## 3. Labeling"""

dataset_labeling_id = "udt_ucf24-labeling1" # @param {"type":"string"}
labler_id = "udt_ucf24-labeler1" # @param {"type":"string"}
labler_name = "demo-name" # @param {"type":"string"}
dataset_labeling_methods = ["manual", "semi-automated"] # @param {"type":"raw"}
dataset_labeling_tools = ["CVAT"] # @param {"type":"raw"}

tdml_object['labeling'] = [{
    'type': 'AI_AbstractLabeling',
    'id': f'{dataset_id}-labeling1',
    'scope': {
        'level': 'dataset',
        'levelDescription': [
          {
            'dataset': dataset_id
          }
        ]
    },
    'labelers': [
        {
          'type': 'AI_Labeler',
          'id': f'{dataset_id}-labeler1',
          'name': labler_name
        }
    ],
    'procedure': {
      'type': 'AI_LabelingProcedure',
      'id': f'{dataset_id}-procedure1',
      "methods": dataset_labeling_methods,
      "tools": dataset_labeling_tools
    }
}]

"""## 4. Data"""

data_purpose = "training" # @param ["training","validation","test","retraining"]

def extract_geopose_params(params_string):
  """
  Extracts the latitude and longitude from a "parameters" string formatted for
  for GeoPose.

  Args:
      params_string (string): String containing GeoPose translation
      and rotation data.
      Ex. "translation=[28.5909266537322, -81.18892360486201, -4.721954339183867]&rotation=[0.3568742498642263, 0.5483800092396545, -0.4091981297088115, 0.6359850680845256]"

  Returns:
      latitude (float): Latitude value.
      longitude (float): Longitude value.
  """
  # Extract all floating point numbers from the string
  float_numbers = re.findall(r"[-+]?\d*\.\d+|\d+", params_string)

  # Convert extracted strings to float numbers
  float_numbers = [float(num) for num in float_numbers]

  # Assign the values to the corresponding labels
  # We expect the order: latitude, longitude, altitude, qx, qy, qz, qw
  if len(float_numbers) != 7:
      raise ValueError(f"Expected 7 floating point numbers, but got {len(float_numbers)}. Extracted values: {float_numbers}")

  latitude, longitude, altitude, qx, qy, qz, qw = float_numbers

  # Return them in a dictionary
  return {
      "latitude": latitude,
      "longitude": longitude,
      "altitude": altitude,
      "qx": qx,
      "qy": qy,
      "qz": qz,
      "qw": qw
  }

# array to hold each training example
data_array = []

# Array of information on each annotated image
annotations_array = annotation_data['annotations']

# Array of information on each annotated image
annotations_category_array = annotation_data['categories']

for image in annotation_data['images']:

  # Get the number in the image name to use as an index for the geopose data
  gp_frame_index = int(re.search(r'\d+', image['file_name']).group(0)) - 1  # CAUTION: Dependent upon image naming scheme img0001.png

  geopose_frame_obj = geopose_data['innerFrameSeries'][gp_frame_index]
  gp_parameters_obj = extract_geopose_params(geopose_frame_obj['parameters'])

  # Get "GPS Time" from ins_data based on gp_frame_index
  # gps_time = ins_data.iloc[gp_frame_index]['GPS time']

  # Extract epoch time from the image name in the synced df file
  epoch_time = ins_data.iloc[gp_frame_index]['image'][:-4]

  # Get annotations for this image
  annotations = [annotation for annotation in annotations_array if annotation['image_id'] == image['id']]

  # Create array of labels for each annotation within this image
  labels = []
  for annotation in annotations:
    category_index = annotation['category_id'] - 1

    labels.append({
        'type': 'AI_ObjectLabel',
        'class': annotations_category_array[category_index]['name'],
        'object': {
            'type': 'Feature',
            'geometry': {
                'type': 'Polygon',
                'coordinates': annotation['segmentation']
            },
            'properties': {
                'bbox': annotation['bbox'],
                'area': annotation['area'],
                'attributes': annotation['attributes']
            }
        }
    })

  data_array.append({
      'type': 'AI_AbstractTrainingData',
      'id': f'annotated_image_{image["id"]}',
      'dataURL': [f'images/{image["file_name"]}'],
      # 'gpsTime': int(gps_time),
      'validTime': int(epoch_time),
      'trainingType': data_purpose,
      'geopose': {
          'authority': geopose_frame_obj['authority'],
          'id': geopose_frame_obj['id'],
          'position': {
            'lat': gp_parameters_obj['latitude'],
            'lon': gp_parameters_obj['longitude'],
            'altitude': gp_parameters_obj['altitude']
            },
          'quaternion': {
            'x': gp_parameters_obj['qx'],
            'y': gp_parameters_obj['qy'],
            'z': gp_parameters_obj['qz'],
            'w': gp_parameters_obj['qw']
          }
      },
      'labels': labels
  })

tdml_object['data'] = data_array

"""# Validate TDML"""

def validate_tdml(tdml):
  mandatory_fields = ['type', 'id', 'name', 'description', 'license', 'tasks', 'data']
  validation_messages = []

  # Ensure each mandatory field has a value
  for field in mandatory_fields:
    if tdml[field] == '' or tdml[field] == []:
      validation_messages.append(f'Field [{field}] must have a value')

  # Show whether TDML is valid
  if len(validation_messages) > 0:
    raise Exception('\n'.join(validation_messages))
  else:
    print('TDML is valid')

# validate tdml
validate_tdml(tdml_object)

"""# Export TDML"""

with open(f'tdml_output_data/{dataset_name}_tdml (validTime).json', 'w') as f:
    json.dump(tdml_object, f, indent=2)
    f.close()

